version: "3.9"
services:
  ili2cws:
    image: sogis/ili2c-web-service:0
    ports:
      - 8080:8080
    restart: unless-stopped
  caddy:
    image: caddy:2.8.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
    restart: unless-stopped
volumes:
  caddy-config: {}
  caddy-data: {}